<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DemoMApplicationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('m_applications')->delete();
        
        \DB::table('m_applications')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Application 1',
                'description' => '<p>Description de l\'application 1</p>',
                'security_need_c' => 1,
                'responsible' => 'RSSI',
                'type' => 'logiciel',
                'technology' => 'Microsoft',
                'external' => NULL,
                'users' => '> 20',
                'created_at' => '2020-06-14 11:20:15',
                'updated_at' => '2022-03-20 18:53:29',
                'deleted_at' => NULL,
                'entity_resp_id' => 2,
                'application_block_id' => 3,
                'documentation' => '//Documentation/application1.docx',
                'security_need_i' => 1,
                'security_need_a' => 1,
                'security_need_t' => 1,
                'version' => '1.2',
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Application 2',
                'description' => '<p><i>Description</i> de l\'<strong>application</strong> 2</p>',
                'security_need_c' => 2,
                'responsible' => 'RSSI',
                'type' => 'progiciel',
                'technology' => 'martian',
                'external' => 'SaaS',
                'users' => '>100',
                'created_at' => '2020-06-14 11:31:16',
                'updated_at' => '2022-02-06 16:52:36',
                'deleted_at' => NULL,
                'entity_resp_id' => 18,
                'application_block_id' => 1,
                'documentation' => 'None',
                'security_need_i' => 2,
                'security_need_a' => 2,
                'security_need_t' => 2,
                'version' => '1.0',
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Application 3',
                'description' => '<p>Test application 3</p>',
                'security_need_c' => 1,
                'responsible' => 'RSSI',
                'type' => 'progiciel',
                'technology' => 'Microsoft',
                'external' => 'Interne',
                'users' => '>100',
                'created_at' => '2020-06-17 19:33:41',
                'updated_at' => '2021-05-15 10:06:53',
                'deleted_at' => NULL,
                'entity_resp_id' => 12,
                'application_block_id' => 2,
                'documentation' => 'Aucune',
                'security_need_i' => 2,
                'security_need_a' => 3,
                'security_need_t' => 3,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Application 4',
                'description' => '<p>Description app4</p>',
                'security_need_c' => 2,
                'responsible' => 'RSSI',
                'type' => 'logiciel',
                'technology' => 'Microsoft',
                'external' => 'Internl',
                'users' => '>100',
                'created_at' => '2020-08-11 16:13:02',
                'updated_at' => '2021-07-11 10:59:57',
                'deleted_at' => NULL,
                'entity_resp_id' => 1,
                'application_block_id' => 2,
                'documentation' => 'None',
                'security_need_i' => 2,
                'security_need_a' => 3,
                'security_need_t' => 2,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'CUST AP01',
                'description' => '<p>Customer appication</p>',
                'security_need_c' => 0,
                'responsible' => NULL,
                'type' => NULL,
                'technology' => 'web',
                'external' => NULL,
                'users' => NULL,
                'created_at' => '2020-08-22 06:58:18',
                'updated_at' => '2020-08-26 16:56:20',
                'deleted_at' => '2020-08-26 16:56:20',
                'entity_resp_id' => NULL,
                'application_block_id' => NULL,
                'documentation' => NULL,
                'security_need_i' => NULL,
                'security_need_a' => NULL,
                'security_need_t' => NULL,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'totototo',
                'description' => NULL,
                'security_need_c' => 0,
                'responsible' => NULL,
                'type' => NULL,
                'technology' => 'totottoo',
                'external' => NULL,
                'users' => NULL,
                'created_at' => '2020-08-22 06:59:26',
                'updated_at' => '2020-08-22 06:59:43',
                'deleted_at' => '2020-08-22 06:59:43',
                'entity_resp_id' => NULL,
                'application_block_id' => NULL,
                'documentation' => NULL,
                'security_need_i' => NULL,
                'security_need_a' => NULL,
                'security_need_t' => NULL,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Windows Word',
                'description' => '<p>Description de l\'application</p>',
                'security_need_c' => 3,
                'responsible' => 'Nestor',
                'type' => 'artificiel',
                'technology' => 'client lourd',
                'external' => NULL,
                'users' => '>100',
                'created_at' => '2020-08-23 10:20:34',
                'updated_at' => '2020-08-26 16:56:23',
                'deleted_at' => '2020-08-26 16:56:23',
                'entity_resp_id' => 10,
                'application_block_id' => 2,
                'documentation' => NULL,
                'security_need_i' => NULL,
                'security_need_a' => NULL,
                'security_need_t' => NULL,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Application 99',
                'description' => NULL,
                'security_need_c' => 1,
                'responsible' => 'André',
                'type' => 'progiciel',
                'technology' => 'client lourd',
                'external' => 'SaaS',
                'users' => '>100',
                'created_at' => '2020-08-23 12:08:02',
                'updated_at' => '2020-08-26 16:56:13',
                'deleted_at' => '2020-08-26 16:56:13',
                'entity_resp_id' => NULL,
                'application_block_id' => NULL,
                'documentation' => NULL,
                'security_need_i' => NULL,
                'security_need_a' => NULL,
                'security_need_t' => NULL,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Test33',
                'description' => '<p>fsfsdfsd</p>',
                'security_need_c' => 0,
                'responsible' => 'Nestor',
                'type' => 'progiciel',
                'technology' => 'martian',
                'external' => NULL,
                'users' => NULL,
                'created_at' => '2020-08-26 16:54:05',
                'updated_at' => '2020-08-26 16:54:35',
                'deleted_at' => '2020-08-26 16:54:35',
                'entity_resp_id' => 10,
                'application_block_id' => NULL,
                'documentation' => NULL,
                'security_need_i' => NULL,
                'security_need_a' => NULL,
                'security_need_t' => NULL,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Test33R',
                'description' => '<p>fsfsdfsd</p>',
                'security_need_c' => 0,
                'responsible' => 'Nestor',
                'type' => 'progiciel',
                'technology' => 'martian',
                'external' => NULL,
                'users' => NULL,
                'created_at' => '2020-08-26 16:54:28',
                'updated_at' => '2020-08-26 16:54:39',
                'deleted_at' => '2020-08-26 16:54:39',
                'entity_resp_id' => 10,
                'application_block_id' => NULL,
                'documentation' => NULL,
                'security_need_i' => NULL,
                'security_need_a' => NULL,
                'security_need_t' => NULL,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'SuperApp',
                'description' => '<p>Supper application</p>',
                'security_need_c' => 0,
                'responsible' => 'RSSI',
                'type' => 'logiciel',
                'technology' => 'martian',
                'external' => NULL,
                'users' => NULL,
                'created_at' => '2021-04-12 16:54:57',
                'updated_at' => '2021-04-12 19:10:44',
                'deleted_at' => '2021-04-12 19:10:44',
                'entity_resp_id' => NULL,
                'application_block_id' => NULL,
                'documentation' => NULL,
                'security_need_i' => NULL,
                'security_need_a' => NULL,
                'security_need_t' => NULL,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'SuperApp',
                'description' => '<p>Super super application !</p>',
                'security_need_c' => 1,
                'responsible' => 'RSSI',
                'type' => 'Web',
                'technology' => 'Oracle',
                'external' => 'Interne',
                'users' => NULL,
                'created_at' => '2021-04-12 19:10:59',
                'updated_at' => '2021-06-23 21:33:15',
                'deleted_at' => NULL,
                'entity_resp_id' => 1,
                'application_block_id' => 2,
                'documentation' => NULL,
                'security_need_i' => 1,
                'security_need_a' => 1,
                'security_need_t' => 1,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'test application',
                'description' => NULL,
                'security_need_c' => 0,
                'responsible' => NULL,
                'type' => NULL,
                'technology' => NULL,
                'external' => NULL,
                'users' => NULL,
                'created_at' => '2021-05-07 10:23:59',
                'updated_at' => '2021-05-07 10:24:03',
                'deleted_at' => '2021-05-07 10:24:03',
                'entity_resp_id' => NULL,
                'application_block_id' => NULL,
                'documentation' => NULL,
                'security_need_i' => NULL,
                'security_need_a' => NULL,
                'security_need_t' => NULL,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Windows Calc',
                'description' => '<p>Calculatrice windows</p>',
                'security_need_c' => 2,
                'responsible' => 'RSSI',
                'type' => 'logiciel',
                'technology' => 'Microsoft',
                'external' => 'Internl',
                'users' => NULL,
                'created_at' => '2021-05-13 10:15:27',
                'updated_at' => '2022-03-20 18:53:29',
                'deleted_at' => NULL,
                'entity_resp_id' => 1,
                'application_block_id' => 3,
                'documentation' => NULL,
                'security_need_i' => 0,
                'security_need_a' => 0,
                'security_need_t' => 0,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Compta',
                'description' => '<p>Application de comptabilité</p>',
                'security_need_c' => 3,
                'responsible' => 'RSSI',
                'type' => 'progiciel',
                'technology' => 'Microsoft',
                'external' => 'Interne',
                'users' => '>100',
                'created_at' => '2021-05-15 09:53:15',
                'updated_at' => '2021-05-15 09:53:15',
                'deleted_at' => NULL,
                'entity_resp_id' => 1,
                'application_block_id' => 2,
                'documentation' => NULL,
                'security_need_i' => 4,
                'security_need_a' => 2,
                'security_need_t' => 3,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Queue Manager',
                'description' => '<p>Queue manager</p>',
                'security_need_c' => 4,
                'responsible' => 'RSSI',
                'type' => 'logiciel',
                'technology' => 'Internal Dev',
                'external' => 'Interne',
                'users' => '>100',
                'created_at' => '2021-08-02 17:17:11',
                'updated_at' => '2021-08-02 17:18:32',
                'deleted_at' => NULL,
                'entity_resp_id' => 1,
                'application_block_id' => 1,
                'documentation' => '//Portal/QueueManager.doc',
                'security_need_i' => 4,
                'security_need_a' => 4,
                'security_need_t' => 4,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'test',
                'description' => NULL,
                'security_need_c' => 0,
                'responsible' => NULL,
                'type' => NULL,
                'technology' => NULL,
                'external' => NULL,
                'users' => NULL,
                'created_at' => '2021-10-10 13:03:24',
                'updated_at' => '2021-10-10 13:03:24',
                'deleted_at' => NULL,
                'entity_resp_id' => NULL,
                'application_block_id' => NULL,
                'documentation' => NULL,
                'security_need_i' => 0,
                'security_need_a' => 0,
                'security_need_t' => 0,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Application 42',
                'description' => '<p>The Ultimate Question of Life, the Universe and Everything</p>',
                'security_need_c' => -1,
                'responsible' => 'Nestor',
                'type' => NULL,
                'technology' => NULL,
                'external' => NULL,
                'users' => NULL,
                'created_at' => '2021-11-15 17:03:20',
                'updated_at' => '2021-12-11 11:06:18',
                'deleted_at' => NULL,
                'entity_resp_id' => NULL,
                'application_block_id' => NULL,
                'documentation' => NULL,
                'security_need_i' => -1,
                'security_need_a' => -1,
                'security_need_t' => 0,
                'version' => NULL,
                'functional_referent' => NULL,
                'editor' => NULL,
                'install_date' => NULL,
                'update_date' => NULL,
                'rto' => NULL,
                'rpo' => NULL,
                'vendor' => NULL,
                'product' => NULL,
            ),
        ));
        
        
    }
}