name: Release Charts
description: Keep chart inde up to date
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
inputs:
  cf_token:
    description: github env cf_token
    required: true
runs:    
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      shell: bash

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.7.0
      with:
        charts_dir: _helm_chart
        skip_existing: true
        mark_as_latest: false
        config: docs/_helm_chart/chart-release-config.yaml
      env:
        CR_TOKEN: "${{ input.cf_token}}"
          
