docs_dir: docs

# Project information
site_name: Mercator
site_description: Mapping the Information System !
site_url: https://dbarzin.githubs.io/mercator/

# Repository
repo_url: https://github.com/dbarzin/mercator
edit_uri: edit/master/docs

# Copyright
copyright: Copyright <a href="https://www.gnu.org/licenses/licenses.en.html">GPL</a>.

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - palette.toggle
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - css/overrides.css

extra:
  generator: false

plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
      reconfigure_material: true

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - index.md
  - application.md
  - cartography.md
  - maturity.md
  - bpmn.md
  - queries.md
  - features.md
  - reports.md
  - vulnerabilities.md
  - usecases.md
  - model.md
  - import.md
  - api.md
  - apifilters.md
  - admin.md
  - config.md
  - references.md

